import type { Metadata } from "next";

import { Girassol } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const neohellenic = localFont({
  src: [
    {
      path: "../public/fonts/GFS_Neohellenic/GFSNeohellenic-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/GFS_Neohellenic/GFSNeohellenic-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-neohellenic",
});

const girassol = Girassol({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-girassol",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${girassol.variable} ${neohellenic.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
